package example.db;

import java.util.ArrayList;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.Session;

import example.db.DBPost.FlatPost;
import example.db.DBUser.FlatUser;

@Entity
@Table(name="blog")
public class DBBlog {
	@Id // specifies that the following field is the primary key for this table, which also means that no two entries in this column may be identical
	@GeneratedValue(strategy=GenerationType.AUTO) // specifies that this field will be automatically generated by the database and should not be specifies manually 
	private long id; // unique id
	
	@ManyToOne // specifies that this field represents a many-to-one relationship, meaning that a single user may own many posts 
    // (in the database this means that the user's id will be stored in a column called author_id, but Hibernate will automatically convert that into a full DBUser object for us)
	private DBUser author; // user who wrote this post
	
	private String title;
	
	private long date;
	
	public FlatBlog flatten() {
		return new FlatBlog(this);
	}
	
	public static class FlatBlog {
		public final long id;
		public final FlatUser author;
		public final String title;
		public final long date;
		public final ArrayList<FlatPost> posts = new ArrayList<>();
		public FlatBlog(DBBlog blog) {
			this.id = blog.getId();
			this.author = blog.getAuthor().flatten();
			this.title = blog.getTitle();
			this.date = blog.getDate();
		}
		public FlatBlog(DBBlog blog, Session session) {
			this.id = blog.getId();
			this.author = blog.getAuthor().flatten();
			this.title = blog.getTitle();
			this.date = blog.getDate();
			session.createQuery("from DBPost post where post.blog.id=" + this.id,DBPost.class).stream().forEach(post->posts.add(post.flatten()));;
		}
	}
	
	public DBBlog() {}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public DBUser getAuthor() {
		return author;
	}

	public void setAuthor(DBUser author) {
		this.author = author;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public long getDate() {
		return date;
	}

	public void setDate(long date) {
		this.date = date;
	}
	
	
}
