package example.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity // marks this class as a database table (database tables are also called entities)
@Table(name="unconfirmeduser") // sets the name of the table in the database
public class DBUnconfirmedUser {
	
	@Id // specifies that the following field is the primary key for this table, which also means that no two entries in this column may be identical
	@GeneratedValue(strategy=GenerationType.AUTO) // specifies that this field will be automatically generated by the database and should not be specifies manually 
	private long id; // unique id
	
	@Column(unique=true) // specifies that no two entries in this column may be identical (even though this column is *not* part of the primary key)
	private String email; // user's email address
	
	private String name; // user's display name (note that these are not required to be unique)
	
	private long timestamp; // date account created
	
	private String hashedPassword;
	
	private String token;
	
	public DBUnconfirmedUser() {} // required empty constructor
	
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}
	
	public String getHashedPassword() {
		return hashedPassword;
	}

	public void setHashedPassword(String hashedPassword) {
		this.hashedPassword = hashedPassword;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}
}
